services:
  - type: web
    name: sellerchamp-item-activate-listing
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SELLERCHAMP_API_TOKEN
        sync: false
      - key: APP_PIN
        sync: false
